[tool.poetry]
name = "cv"
version = "0.1.0"
description = "My personal Django Portifolio"
authors = ["Luã Bida Vacaro <luabidaa@gmail.com>"]
license = "GNU"
readme = "README.md"
# packages = [{include = "src"}]


[tool.poetry.dependencies]
python = ">=3.8.1,<4.0.0"
django-ninja = "^0.21.0"
django-extensions = "^3.2.1"
dr-scaffold = "^2.1.2"
jinja2 = "<3.0.3"
psycopg2-binary = "^2.9.6"
django = "^4.2.2"
containers-sugar = "^1.7.0"
docker-compose = "^1.29.2"
whitenoise = "^6.5.0"


[tool.poetry.group.pre-commit.dependencies]
pre-commit = "^3.3.2"
black = "^23.3.0"
ruff = "^0.0.272"


[tool.poetry.group.dev.dependencies]
makim = "^1.8.1"
pygments = "^2.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
