version: '3.4'

services:
  postgres:
    platform: linux/amd64
    hostname: postgres
    restart: unless-stopped
    build:
      context: ..
      dockerfile: containers/postgres/Dockerfile
      args:
        # note: if you want to use a specific UID and GID, ensure to add it to
        #       the .env file
        - UID=${POSTGRES_HOST_UID}
        - GID=${POSTGRES_HOST_GID}
        - DATA_DIR=${POSTGRES_DATA_DIR_HOST}
        - environment=${ENV}
    env_file:
      - ../.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    user: "${POSTGRES_HOST_UID}:${POSTGRES_HOST_GID}"
    volumes:
      - ${POSTGRES_DATA_DIR_HOST}/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ${POSTGRES_DATA_DIR_HOST}/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER}"]
      interval: 60s
      timeout: 5s
      retries: 10
    command: -p ${POSTGRES_PORT}
